# Elixir CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: mix dialyzer
