# Elixir CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-cache-{{ checksum "mix.lock" }}
            - v2-deps-cache
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix coveralls.circle
      - run: mix dialyzer
      - save_cache:
          key: v2-deps-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix`
